### ISSUE TITLE
Code released 

### ISSUE THREAD

**Issue by zzs95** [lichen14/AttENT#1]
Hi. May I ask, when your team will release the code?

**Comment by lichen14** [comment]
First of all, thank you for your attention to our work. 
We have released some results, including pre-trained models, well-trained models, and some translated data samples. 
We will release the rest of the core code after this work is accepted by the conference. 
Finally, if you want, you can star our work.

**Comment by zzs95** [comment]
Thank you for your reply. We are looking forward to it. That will help us a lot.
