### ISSUE TITLE
CycleGan代码和数据预处理

### ISSUE THREAD

**Issue by lzy-whut** [lichen14/AttENT#2]
您好，是否方便上传下您训练gan的代码和数据预处理的代码？

**Comment by lichen14** [comment]
Hi lzy,
The ReadMe illustrated that the training process of CycleGAN is similar to the project [PyTorch-CycleGAN](https://github.com/aitorzip/PyTorch-CycleGAN).
Differently, we use the attention CycleGAN, and the code is also released at [Generator5](https://github.com/lichen14/AttENT/blob/main/attent/models.py). 
You just need to replace this [code](https://github.com/aitorzip/PyTorch-CycleGAN/blob/67da8f9e2b69bd68763451803c7700aaccc92f18/train#L12) with 'from models import Generator5'.
The rest of the training process is consistent with the original project.

As for the preprocessing code, it is now lost as it was a long time ago. 
The good news is that I found a similar code in the code base, whose reliability is **NOT** verified.
I upload it at [preprocessing.py](https://github.com/lichen14/AttENT/blob/main/attent/dataset/preprocessing.py) and hope it will help you.

Thanks for your interest in this work.

Best,
Chen
