### ISSUE TITLE
How to visualize the entropy information

### ISSUE THREAD

**Issue by TshellT** [lichen14/AttENT#3]
Dear author,
How to visualize the entropy information map, could you provide the code for visualizing the entropy information map?
Thanks!
![image](https://github.com/lichen14/AttENT/assets/28928231/410fa8f7-a5da-409c-9cda-940497bc1e0b)

**Comment by lichen14** [comment]
Hi,
Sorry for the late reply.
1. The output of the entropy output can be obtained by this line of [code](https://github.com/lichen14/AttENT/blob/adb30677bf9e86825d9716dc477a9c9daa6e16a9/attent/domain_adaptation/eval_UDA_stats.py#L127) or the function [prob_2_entropy](https://github.com/lichen14/AttENT/blob/adb30677bf9e86825d9716dc477a9c9daa6e16a9/attent/domain_adaptation/train_UDA_tmp0.py#L122).
2. Regarding the visualization of the entropy map, we provide a way to implement it for reference:
`
import seaborn as sns
`
`
sns_plt = sns.heatmap(output_ent, robust=True, cbar=False, square=True, cmap='jet')
`
`
plt.savefig(osp.join(PATH+'/entropy/', NAME) ,bbox_inches = 'tight')
`
`
plt.axis('off')
`
`
plt.show()
`

Best,
Chen

**Comment by TshellT** [comment]
> Hi, Sorry for the late reply.
> 
> 1. The output of the entropy output can be obtained by this line of [code](https://github.com/lichen14/AttENT/blob/adb30677bf9e86825d9716dc477a9c9daa6e16a9/attent/domain_adaptation/eval_UDA_stats.py#L127) or the function [prob_2_entropy](https://github.com/lichen14/AttENT/blob/adb30677bf9e86825d9716dc477a9c9daa6e16a9/attent/domain_adaptation/train_UDA_tmp0.py#L122).
> 2. Regarding the visualization of the entropy map, we provide a way to implement it for reference:
>    `import seaborn as sns`
>    `sns_plt = sns.heatmap(output_ent, robust=True, cbar=False, square=True, cmap='jet')`
>    `plt.savefig(osp.join(PATH+'/entropy/', NAME) ,bbox_inches = 'tight')`
>    `plt.axis('off')`
>    `plt.show()`
> 
> Best, Chen

Thanks!
Best wishes!
